version: '3.9'

services:
    web:
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - ./:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        environment:
            NGINX_SERVER_ROOT: /var/www/html/public

    php:
        container_name: "php-fpm"
        build:
            context: images/php
        volumes:
            - ./:/var/www/html
